.TH "Source/Crawler/Worker.hpp" 3 "Sun Jun 21 2015" "Version 1.0" "Crawler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Crawler/Worker.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Crawler/Linker\&.hpp>\fP
.br
\fC#include <SFML/System\&.hpp>\fP
.br
\fC#include <string>\fP
.br
\fC#include <memory>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCrawler::Worker\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsf\fP"
.br
.ti -1c
.RI " \fBCrawler\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Crawler from the source code\&.
